apiVersion: v1
kind: Service
metadata:
  name: anomaly-backend
  namespace: anomaly
  labels:
    app: anomaly-backend
spec:
  type: ClusterIP
  selector:
    app: anomaly-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000

