apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-ui
  namespace: anomaly
  labels:
    app: anomaly-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: anomaly-ui
    spec:
      containers:
        - name: ui
          image: anomaly-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
              name: http
          env:
            - name: BACKEND_URL
              value: http://anomaly-backend:8000
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

